Enemy fixes
Nullptr-Studios/Project-Hotline pull request #105
Opened 2024-10-22 18:36 UTC by dariormt

2024-10-22 18:37 UTC, dariormt commented
Melee weapon support for the enemy is still under development :)

2024-10-22 19:04 UTC, ynks commented
do we merge this branches to #92 or to dev directly?

2024-10-23 08:28 UTC, ynks requested changes
Fix the input

2024-10-23 08:28 UTC, ynks commented on Assets/Enemy/EnemyDamageable.cs
> +using Unity.VisualScripting;
jiji

2024-10-23 08:28 UTC, ynks commented on Assets/Player/PlayerInput.cs
> +        _input.Gameplay.SwitchWeapons.Enable();
```suggestion
       playerWeaponManager.EnableInput();
```

2024-10-23 12:54 UTC, ynks approved these changes

2024-10-23 12:54 UTC, ynks commented on Assets/Player/PlayerWeaponManager.cs
> +using UnityEngine.Windows;
```cpp
#using "window.h"
```
🤓

2024-10-23 13:07 UTC, merged